print("========== COMMANDS ==========")
print("uninstall - Uninstall the OS")
print("update - Update the OS")
print("music - Plays inserted music")
print("env - Prints environment variables")
print("matrix - Print matrix rain")
print("home - Navigate back to Home GUI")
print("==============================")