print("Updating OS...")
sleep(2)
shell.run("cd /.system")
shell.run("wget https://raw.githubusercontent.com/WolftekEntertainment/ComputerCraft/installation/startup.lua installer.lua")
shell.run("installer.lua skipreboot")